steps:
  - name: ":golang: Tests"
    key: test
    command: .buildkite/steps/tests.sh
    plugins:
      - docker#v3.1.0:
          image: "golang:1.24"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler

  - name: ":hammer::lambda: Build Lambda"
    key: build
    command: .buildkite/steps/build-lambda.sh
    artifact_paths:
      - handler.zip

  - label: ":lambda::arrow_right::package: Create SAR Package"
    key: package
    command: .buildkite/steps/sar.sh
    depends_on:
      - test
      - build
    plugins:
      - aws-assume-role-with-web-identity#v1.1.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-aws-stack-buildkite-agent-scaler-publish

  - block: ":package::arrow_right::rocket: Draft :github: Release Approved?"
    key: release
    depends_on:
      - package

  - label: ":package::arrow_right::aws: Publish SAR Package"
    key: publish
    command: .buildkite/steps/publish-package.sh
    depends_on:
      - release
    plugins:
      - aws-assume-role-with-web-identity#v1.1.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-aws-stack-buildkite-agent-scaler-publish
