# YAML anchor for mise setup
x-mise-setup: &mise-setup |
  if [[ ! -f ./bin/mise ]]; then
    mkdir -p ./bin
    curl -fsSL https://mise.jdx.dev/mise-latest-linux-x64 > ./bin/mise
    chmod +x ./bin/mise
  fi
  ./bin/mise install

steps:
  - name: ":golang: Tests"
    key: test
    commands:
      - *mise-setup
      - .buildkite/steps/tests.sh

  - name: ":hammer::lambda: Build Lambda"
    key: build
    commands:
      - *mise-setup
      - .buildkite/steps/build-lambda.sh
    artifact_paths:
      - handler.zip

  - label: ":lambda::arrow_right::package: Create SAR Package"
    key: package
    command: .buildkite/steps/sar.sh
    depends_on:
      - test
      - build
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-aws-stack-buildkite-agent-scaler-publish
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug

  - block: ":package::arrow_right::rocket: Draft :github: Release Approved?"
    key: release
    depends_on:
      - package

  - label: ":package::arrow_right::aws: Publish SAR Package"
    key: publish
    command: .buildkite/steps/publish-package.sh
    depends_on:
      - release
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-aws-stack-buildkite-agent-scaler-publish
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
