agents:
  queue: elastic-runners

steps:
- label: ":s3: Remove from {{matrix}} S3 Release Location"
  key: s3-release
  command: .buildkite/steps/remove-from-s3 release {{matrix}}
  plugins:
  - aws-assume-role-with-web-identity:
      role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-buildkite-agent-scaler
  matrix:
  - vv1.4.0
  - 1.5.1
